### ISSUE TITLE
Unsupported arch: ia32 - linux?

### ISSUE THREAD

**Issue by davidkonrad** [cubbit/enigma#1]
Hi! Looks promising. I tried it out as :

```
git clone https://github.com/cubbit/enigma.git 
cd enigma 
npm install
```
everything seem to go alright until the install runs `node-gyp rebuild `: 

```
make: Entering directory `/var/www/html/valg/lib/enigma/build'
  ACTION Prepare dependencies /var/www/html/valg/lib/enigma/dependencies
Error: Unsupported arch: ia32 - linux
    at dependencies (/var/www/html/valg/lib/enigma/scripts/node/dependencies.js:70:27)
    at Object.<anonymous> (/var/www/html/valg/lib/enigma/scripts/node/dependencies.js:106:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
Not sure what it is, and how to solve it. Just runnng on a laptup with ubuntu 14.04.

**Comment by marmos91** [comment]
Hi @davidkonrad, thank you for reporting this issue. For sure, this is related to how we build the openssl WebAssembly. I will open a Pull Request to try addressing it.

**Comment by marmos91** [comment]
@davidkonrad can you try building from branch `hotfix/ia32`?

**Comment by davidkonrad** [comment]
Thank you for replying! And sorry for late feedback.  Trying `git fetch` -> `git checkout hotfix/ia32` ->` git pull` (Already up-to-date) -> `npm install` 

Already dramatically progress, it seem to come much, much longer in the build process now, a lot of compile output indicates it works well, but it halts at 

```
make depend
making depend in crypto...
make[1]: Entering directory `/var/www/html/valg/lib/enigma/dependencies/openssl/crypto'
../util/domd: 23: ../util/domd: makedepend: not found
mv: cannot stat 'Makefile.new': No such file or directory
make[1]: *** [local_depend] Error 127
make[1]: Leaving directory `/var/www/html/valg/lib/enigma/dependencies/openssl/crypto'
make: *** [depend] Error 1
Error: Unable to prepare module
    at dependencies (/var/www/html/valg/lib/enigma/scripts/node/dependencies.js:102:19)
    at Object.<anonymous> (/var/www/html/valg/lib/enigma/scripts/node/dependencies.js:109:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

```
Have the feeling it is really close, perhaps just a missing file?
